### ISSUE TITLE
Lock scroller when child rows are shown

### ISSUE THREAD

**Issue by prog8** [DataTables/Scroller#58]
In general child rows in datatables can be much larger (contains more data) than standard rows. This makes DT scroller break somehow. When I open child row which is very high and I scroll down to see the entire rows scroller starts it work and reloads the DT page. I think scroller should be locked in the same position page until all child rows are opened. Any opinions about this?

**Comment by DataTables** [comment]
I can't really see any way for Scroller to operate correctly with child rows. The issue is that Scroller needs to calculate the position of the table in the scrolling table, which it can only do is all rows are of an equal height and there are no extra elements. If you introduce child rows, then they would need to be taken into account, but that would make the calculations really rather difficult.

I'm afraid that this is not a feature than I am planning on adding to Scroller.

**Comment by prog8** [comment]
I was wondering if it is possible to say "hold on scroller, child rows are opened now so lets freeze". I mean that scroller can be disabled temporarily when child rows are opened and can be enabled again if they are closed. Even if there is no direct support for child rows why cannot be a feature to temporarily disable scroller?

**Comment by DataTables** [comment]
As an end user I'm not sure I would like scrolling being disabled. Perhaps showing a modal rather than a child row would be an option? There is currently no API to enable and disable scroller - although you could use a little Javascript to disable scrolling if you wished.
